# -*- coding: utf-8 -*-
"""
通用函数伪代码导出器 V3.5.0 IDA 9.3 稳定核心
===========================================

本模块只在 IDA / IDAPython 进程内导入。
本模块由交互式插件调用，负责筛选、短路径、检查点、缓存清理、
隔离、按类目录分类和报告归档。
"""
from __future__ import annotations

import csv
import fnmatch
import gc
import hashlib
import json
import os
import re
import time
import traceback
import tempfile
from collections import Counter, deque
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Optional, Sequence, Set, Tuple

import ida_auto
import ida_diskio
import ida_funcs
import ida_hexrays
import ida_kernwin
import ida_lines
import ida_loader
import ida_nalt
import ida_segment
import idautils
import idc

CORE_VERSION = "3.5.1-ida93-pyside6-zh"
CONFIG_SCHEMA_VERSION = 10

SCOPE_OPTIONS: Tuple[Tuple[str, str], ...] = (
    ("all_internal", "导出全部保留的内部函数"),
    ("matched_only", "仅导出符合包含条件的函数"),
    ("matched_with_dependencies", "导出匹配函数，并递归补齐内部依赖"),
    ("current_only", "仅导出当前光标所在函数"),
    ("current_with_dependencies", "导出当前函数，并递归补齐内部依赖"),
    ("range_only", "导出指定地址范围内的函数"),
    ("range_with_dependencies", "导出指定地址范围内的函数，并递归补齐内部依赖"),
)


FILENAME_OPTIONS: Tuple[Tuple[str, str], ...] = (
    ("auto_readable", "自动优化：尽量保留可读名称（推荐）"),
    ("address_only", "最短命名：仅地址 + 哈希"),
)

DEFAULT_CONFIG = {
    "config_schema_version": CONFIG_SCHEMA_VERSION,
    "output_dir": "",
    "resume_run_dir": "",
    # 界面主题：跟随 IDA、柔和深色或柔和灰色。
    "ui_theme": "soft_dark",
    "scope": "all_internal",
    "range_start": "0x0",
    "range_end": "0x0",
    "maximum_dependency_depth": 0,
    "include_exact_names": [],
    "include_prefixes": [],
    "include_contains": [],
    "include_globs": [],
    "include_regex": "",
    "exclude_exact_names": [],
    "exclude_prefixes": [],
    "exclude_contains": [],
    "exclude_globs": [],
    "exclude_regex": "",
    "force_include_prefixes": [],
    "include_segments": [],
    "exclude_segments": [],
    "case_sensitive_filters": False,
    "skip_imported_functions": True,
    "skip_external_segments": True,
    "skip_non_executable_segments": True,
    "skip_ida_library_functions": True,
    "skip_standard_cpp_names": True,
    "skip_common_c_names": True,
    "skip_runtime_helpers": True,
    "skip_known_third_party_names": False,
    "skip_thunks": False,
    "skip_autogenerated_names": False,
    "minimum_function_length": 0,
    "maximum_function_length": 0,
    "maximum_export_count": 0,
    "dry_run": False,
    "confirm_before_export": True,
    "skip_existing_files_when_resuming": True,
    "group_files_by_segment": False,
    "group_files_by_class": True,
    "class_folder_include_namespaces": True,
    # 路径长度由插件自动优化。以下参数仅作为内部兼容项保留，不再要求用户填写。
    "auto_path_shortening": True,
    "auto_compact_root_on_overflow": True,
    "compact_output_root": "",
    "internal_path_budget_override": 0,
    "class_folder_component_length": 72,
    # 批次目录：避免单个目录堆积过多函数文件。按目标函数顺序稳定分组，便于续导。
    "group_files_by_batch": True,
    "functions_per_batch_folder": 1000,
    "write_dependency_edges": True,
    "write_tracebacks": False,
    "filename_mode": "auto_readable",
    "maximum_full_path_length": 0,  # 旧版兼容字段；0 表示自动预算。
    "maximum_readable_name_length": 160,  # 内部可读名称预算，不在普通界面展示。
    "progress_update_interval": 50,
    "flush_interval": 10,
    # 稳定模式：默认偏保守，优先避免长时间运行末尾崩溃。
    "stable_mode": True,
    "write_active_checkpoint": True,
    "auto_quarantine_previous_active_on_resume": True,
    "clear_target_cache_after_each_function": True,
    "clear_all_cache_interval": 25,
    "python_gc_interval": 25,
    "cooldown_milliseconds": 0,
    "maximum_functions_per_session": 0,
    "retry_failed_after_local_analysis": False,
    "wait_for_global_auto_analysis": False,
}

LIST_CONFIG_KEYS: Tuple[str, ...] = (
    "include_exact_names", "include_prefixes", "include_contains", "include_globs",
    "exclude_exact_names", "exclude_prefixes", "exclude_contains", "exclude_globs",
    "force_include_prefixes", "include_segments", "exclude_segments",
)

STANDARD_LIBRARY_PREFIXES: Tuple[str, ...] = (
    "std::", "std::__1::", "__gnu_cxx::", "__cxxabiv1::",
    "typeinfo for std::", "vtable for std::", "guard variable for std::",
)
STANDARD_LIBRARY_MANGLED_PREFIXES: Tuple[str, ...] = (
    "_ZNSt", "__ZNSt", "_ZNKSt", "__ZNKSt", "_ZSt", "__ZSt",
    "_ZN9__gnu_cxx", "__ZN9__gnu_cxx", "_ZN10__cxxabiv1", "__ZN10__cxxabiv1",
)
RUNTIME_PREFIXES: Tuple[str, ...] = (
    "__cxa_", "___cxa_", "_Unwind_", "__Unwind_", "__stack_chk_", "___stack_chk_",
    "__clang_call_terminate", "___clang_call_terminate", "__gxx_personality",
    "___gxx_personality", "_objc_", "___objc_", "__asan_", "___asan_",
    "__ubsan_", "___ubsan_", "__tsan_", "___tsan_",
)
RUNTIME_EXACT_NAMES: Set[str] = {
    "operator new", "operator new[]", "operator delete", "operator delete[]",
    "___chkstk_darwin", "__chkstk_darwin", "___chkstk", "__chkstk", "_chkstk",
    "abort", "exit", "_exit",
}
COMMON_C_LIBRARY_NAMES: Set[str] = {
    "malloc", "calloc", "realloc", "free", "memcpy", "memmove", "memset", "memcmp", "memchr",
    "strlen", "strnlen", "strcmp", "strncmp", "strcasecmp", "strncasecmp", "strcpy", "strncpy",
    "strcat", "strncat", "strchr", "strrchr", "strstr", "strtok", "strtok_r", "strdup", "strndup",
    "printf", "fprintf", "sprintf", "snprintf", "vprintf", "vfprintf", "vsprintf", "vsnprintf",
    "puts", "fputs", "putchar", "fputc", "scanf", "fscanf", "sscanf", "fopen", "fclose", "fread",
    "fwrite", "fseek", "ftell", "fflush", "feof", "ferror", "atoi", "atol", "atoll", "strtol",
    "strtoul", "strtoll", "strtoull", "strtod", "strtof", "time", "clock", "getenv", "setenv",
    "unsetenv", "abs", "labs", "llabs", "sqrt", "sqrtf", "pow", "powf", "floor", "floorf",
    "ceil", "ceilf", "round", "roundf", "sin", "sinf", "cos", "cosf", "tan", "tanf", "isalnum",
    "isalpha", "isdigit", "isspace", "tolower", "toupper", "raise", "signal", "system",
}
KNOWN_THIRD_PARTY_PREFIXES: Tuple[str, ...] = (
    "v8::", "__ZN2v8", "_ZN2v8", "blink::", "__ZN5blink", "_ZN5blink",
    "Skia::", "skia::", "__ZN4skia", "_ZN4skia", "third_party::",
)
WINDOWS_RESERVED_NAMES: Set[str] = {
    "CON", "PRN", "AUX", "NUL", *(f"COM{i}" for i in range(1, 10)), *(f"LPT{i}" for i in range(1, 10))
}


@dataclass(frozen=True)
class ExportTarget:
    start_ea: int
    end_ea: int
    raw_name: str
    display_name: str
    segment_name: str
    flags: int

    @property
    def length(self) -> int:
        return max(0, self.end_ea - self.start_ea)

    def to_json(self) -> dict:
        return {
            "start_ea": self.start_ea,
            "end_ea": self.end_ea,
            "raw_name": self.raw_name,
            "display_name": self.display_name,
            "segment_name": self.segment_name,
            "flags": self.flags,
            "length": self.length,
        }

    @staticmethod
    def from_json(data: dict) -> "ExportTarget":
        return ExportTarget(
            int(data["start_ea"]), int(data["end_ea"]), str(data["raw_name"]),
            str(data.get("display_name") or data["raw_name"]), str(data.get("segment_name") or ""),
            int(data.get("flags", 0)),
        )


@dataclass(frozen=True)
class SkippedTarget:
    start_ea: int
    name: str
    segment_name: str
    reason: str


@dataclass
class ExportStats:
    target_count: int = 0
    exported_count: int = 0
    existing_count: int = 0
    failed_count: int = 0
    quarantined_count: int = 0
    filtered_count: int = 0
    cancelled: bool = False
    dry_run: bool = False
    session_limit_reached: bool = False


@dataclass
class ProcessResult:
    stats: ExportStats
    failures: Counter
    run_dir: Path
    attempt_dir: Path
    remaining_addresses: List[int]
    quarantined_addresses: List[int]


Logger = Callable[[str], None]
CancelChecker = Callable[[], bool]
ProgressCallback = Callable[[int, int, ExportStats, ExportTarget], None]


def default_logger(message: str) -> None:
    now = time.strftime("%H:%M:%S")
    line = f"[通用函数伪代码导出器 {now}] {message}\n"
    try:
        ida_kernwin.msg(line)
    except Exception:
        print(line, end="")


def timestamp_id() -> str:
    return f"{time.strftime('%Y%m%d_%H%M%S')}_{int(time.time() * 1000) % 1000:03d}"


def get_option_label(options: Sequence[Tuple[str, str]], key: str) -> str:
    for option_key, label in options:
        if option_key == key:
            return label
    return key


def split_text_list(text: str) -> List[str]:
    return [item.strip() for item in re.split(r"[;\r\n]+", text or "") if item.strip()]


def deduplicate_strings(values: Iterable[str]) -> List[str]:
    result: List[str] = []
    seen: Set[str] = set()
    for value in values:
        item = str(value).strip()
        if not item or item in seen:
            continue
        seen.add(item)
        result.append(item)
    return result


def normalize_list(value) -> List[str]:
    if isinstance(value, str):
        return deduplicate_strings(split_text_list(value))
    if isinstance(value, (list, tuple, set)):
        return deduplicate_strings(value)
    return []


def parse_integer(value, default: int = 0) -> int:
    if isinstance(value, int):
        return value
    raw = str(value or "").strip()
    if not raw:
        return default
    try:
        return int(raw, 0)
    except ValueError:
        try:
            return int(raw, 16)
        except ValueError:
            return default


def deep_merge_config(base: dict, override: dict) -> dict:
    result = dict(base)
    for key, value in override.items():
        if key in result:
            result[key] = value
    return result


def normalize_config(cfg: dict) -> dict:
    merged = deep_merge_config(DEFAULT_CONFIG, cfg or {})
    for key in LIST_CONFIG_KEYS:
        merged[key] = normalize_list(merged.get(key, []))
    int_keys = (
        "maximum_dependency_depth", "minimum_function_length", "maximum_function_length",
        "maximum_export_count", "maximum_full_path_length", "maximum_readable_name_length",
        "progress_update_interval", "flush_interval", "clear_all_cache_interval",
        "python_gc_interval", "cooldown_milliseconds", "maximum_functions_per_session",
        "class_folder_component_length", "functions_per_batch_folder",
        "internal_path_budget_override",
    )
    for key in int_keys:
        merged[key] = parse_integer(merged.get(key, DEFAULT_CONFIG[key]), int(DEFAULT_CONFIG[key]))
    for key in int_keys:
        merged[key] = max(0, int(merged[key]))
    # 路径预算由平台和输出根目录自动决定。旧版 maximum_full_path_length 仅作为兼容字段保留。
    merged["maximum_full_path_length"] = max(0, merged["maximum_full_path_length"])
    merged["internal_path_budget_override"] = max(0, merged["internal_path_budget_override"])
    merged["progress_update_interval"] = max(1, merged["progress_update_interval"])
    merged["flush_interval"] = max(1, merged["flush_interval"])
    merged["class_folder_component_length"] = max(16, merged["class_folder_component_length"])
    merged["functions_per_batch_folder"] = max(1, merged["functions_per_batch_folder"])
    if merged.get("filename_mode") == "short_hash":
        merged["filename_mode"] = "auto_readable"
    if merged.get("scope") not in {key for key, _ in SCOPE_OPTIONS}:
        merged["scope"] = "all_internal"
    if merged.get("filename_mode") not in {key for key, _ in FILENAME_OPTIONS}:
        merged["filename_mode"] = "auto_readable"
    if merged.get("ui_theme") not in {"follow_ida", "soft_dark", "soft_gray"}:
        merged["ui_theme"] = "soft_dark"
    merged["config_schema_version"] = CONFIG_SCHEMA_VERSION
    return merged


def validate_regex(pattern: str, label: str, case_sensitive: bool) -> None:
    if not pattern:
        return
    try:
        re.compile(pattern, 0 if case_sensitive else re.IGNORECASE)
    except re.error as exc:
        raise RuntimeError(f"{label}不是有效正则表达式：{exc}") from exc


def has_include_filters(cfg: dict) -> bool:
    return bool(cfg["include_exact_names"] or cfg["include_prefixes"] or cfg["include_contains"] or cfg["include_globs"] or cfg["include_regex"])


def validate_config(cfg: dict) -> None:
    validate_regex(cfg["include_regex"], "包含正则表达式", cfg["case_sensitive_filters"])
    validate_regex(cfg["exclude_regex"], "排除正则表达式", cfg["case_sensitive_filters"])
    if cfg["maximum_function_length"] and cfg["minimum_function_length"] > cfg["maximum_function_length"]:
        raise RuntimeError("最小函数长度不能大于最大函数长度。")
    if cfg["scope"].startswith("range_"):
        start, end = parse_integer(cfg["range_start"]), parse_integer(cfg["range_end"])
        if start <= 0 or end <= start:
            raise RuntimeError("地址范围无效，请填写正确的起始地址和结束地址。")
    if cfg["scope"].startswith("matched_") and not has_include_filters(cfg):
        raise RuntimeError("按名称匹配导出时，至少填写一种包含条件。")


def load_json(path: Path) -> dict:
    if not path.is_file():
        return {}
    with path.open("r", encoding="utf-8") as f:
        data = json.load(f)
    return data if isinstance(data, dict) else {}


def atomic_write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temp = path.with_name(path.name + ".tmp")
    try:
        temp.write_text(text, encoding="utf-8", errors="replace")
        os.replace(str(temp), str(path))
    finally:
        try:
            if temp.exists():
                temp.unlink()
        except Exception:
            pass


def atomic_write_json(path: Path, data: object) -> None:
    atomic_write_text(path, json.dumps(data, ensure_ascii=False, indent=2) + "\n")


def append_jsonl(path: Path, data: object) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as f:
        f.write(json.dumps(data, ensure_ascii=False) + "\n")
        f.flush()


def try_demangle(name: str) -> str:
    try:
        return idc.demangle_name(name, idc.get_inf_attr(idc.INF_SHORT_DN)) or ""
    except Exception:
        return ""


def symbol_names(raw_name: str) -> Tuple[str, ...]:
    demangled = try_demangle(raw_name)
    return (raw_name, demangled) if demangled and demangled != raw_name else (raw_name,)


def normalize_match_values(values: Iterable[str], case_sensitive: bool) -> Tuple[str, ...]:
    return tuple(values) if case_sensitive else tuple(value.lower() for value in values)


def exact_matches(names: Iterable[str], patterns: Sequence[str], case_sensitive: bool) -> bool:
    if not patterns:
        return False
    return bool(set(normalize_match_values(names, case_sensitive)) & set(normalize_match_values(patterns, case_sensitive)))


def starts_with_any(names: Iterable[str], patterns: Sequence[str], case_sensitive: bool) -> bool:
    if not patterns:
        return False
    normalized_patterns = normalize_match_values(patterns, case_sensitive)
    return any(name.startswith(normalized_patterns) for name in normalize_match_values(names, case_sensitive))


def contains_any(names: Iterable[str], patterns: Sequence[str], case_sensitive: bool) -> bool:
    if not patterns:
        return False
    ns, ps = normalize_match_values(names, case_sensitive), normalize_match_values(patterns, case_sensitive)
    return any(pattern in name for name in ns for pattern in ps)


def glob_matches(names: Iterable[str], patterns: Sequence[str], case_sensitive: bool) -> bool:
    if not patterns:
        return False
    ns, ps = normalize_match_values(names, case_sensitive), normalize_match_values(patterns, case_sensitive)
    return any(fnmatch.fnmatchcase(name, pattern) for name in ns for pattern in ps)


def regex_matches(names: Iterable[str], pattern: str, case_sensitive: bool) -> bool:
    if not pattern:
        return False
    regex = re.compile(pattern, 0 if case_sensitive else re.IGNORECASE)
    return any(regex.search(name) is not None for name in names)


def matches_include_filters(names: Iterable[str], cfg: dict) -> bool:
    cs = cfg["case_sensitive_filters"]
    return (
        exact_matches(names, cfg["include_exact_names"], cs)
        or starts_with_any(names, cfg["include_prefixes"], cs)
        or contains_any(names, cfg["include_contains"], cs)
        or glob_matches(names, cfg["include_globs"], cs)
        or regex_matches(names, cfg["include_regex"], cs)
    )


def matches_exclude_filters(names: Iterable[str], cfg: dict) -> Optional[str]:
    cs = cfg["case_sensitive_filters"]
    if exact_matches(names, cfg["exclude_exact_names"], cs):
        return "命中自定义排除精确名称"
    if starts_with_any(names, cfg["exclude_prefixes"], cs):
        return "命中自定义排除前缀"
    if contains_any(names, cfg["exclude_contains"], cs):
        return "命中自定义排除子串"
    if glob_matches(names, cfg["exclude_globs"], cs):
        return "命中自定义排除通配符"
    if regex_matches(names, cfg["exclude_regex"], cs):
        return "命中自定义排除正则表达式"
    return None


def segment_matches(name: str, patterns: Sequence[str]) -> bool:
    if not patterns:
        return False
    lowered = name.lower()
    return any(fnmatch.fnmatchcase(lowered, pattern.lower()) for pattern in patterns)


def is_standard_cpp(names: Iterable[str]) -> bool:
    return any(name.startswith(STANDARD_LIBRARY_PREFIXES) or name.startswith(STANDARD_LIBRARY_MANGLED_PREFIXES) for name in names)


def is_common_c(names: Iterable[str]) -> bool:
    for name in names:
        stripped = name.strip()
        variants = {stripped, stripped.lstrip("_")}
        if stripped.startswith("__imp_"):
            variants.add(stripped[len("__imp_"):].lstrip("_"))
        if variants & COMMON_C_LIBRARY_NAMES:
            return True
    return False


def is_runtime(names: Iterable[str]) -> bool:
    return any(name.strip() in RUNTIME_EXACT_NAMES or name.strip().startswith(RUNTIME_PREFIXES) for name in names)


def is_third_party(names: Iterable[str]) -> bool:
    return any(name.startswith(KNOWN_THIRD_PARTY_PREFIXES) for name in names)


def is_autogenerated(name: str) -> bool:
    return bool(re.match(r"^(sub_|nullsub_|loc_|j_|unknown_)", name))


def get_segment_name(ea: int) -> str:
    try:
        segment = ida_segment.getseg(ea)
        return ida_segment.get_segm_name(segment) if segment is not None else ""
    except Exception:
        return ""


def get_database_path() -> Path:
    try:
        path = ida_loader.get_path(ida_loader.PATH_TYPE_IDB)
    except Exception:
        path = ""
    if path:
        return Path(path)
    raise RuntimeError("当前数据库尚未保存为 IDB/I64。请先保存数据库。")


def get_default_output_root() -> Path:
    try:
        path = get_database_path()
        return path.parent / f"{path.stem}_pseudocode_export"
    except Exception:
        try:
            input_path = idc.get_input_file_path()
        except Exception:
            input_path = ""
        if input_path:
            path = Path(input_path)
            return path.parent / f"{path.stem}_pseudocode_export"
        return Path.cwd() / "ida_pseudocode_export"


def collect_import_addresses(logger: Logger = default_logger) -> Set[int]:
    addresses: Set[int] = set()
    try:
        module_count = int(ida_nalt.get_import_module_qty())
    except Exception:
        return addresses

    def callback(ea, name, ordinal):
        addresses.add(int(ea))
        return True

    for module_index in range(module_count):
        try:
            ida_nalt.enum_import_names(module_index, callback)
        except Exception as exc:
            logger(f"警告：枚举导入模块 {module_index} 失败：{exc}")
    return addresses


def classify_skip(func, import_addresses: Set[int], cfg: dict) -> Optional[str]:
    ea = int(func.start_ea)
    raw_name = ida_funcs.get_func_name(ea) or f"sub_{ea:X}"
    names = symbol_names(raw_name)
    segment_name = get_segment_name(ea)
    segment = ida_segment.getseg(ea)
    if segment is None:
        return "缺少所属段信息"
    if cfg["skip_external_segments"]:
        external_type = getattr(ida_segment, "SEG_XTRN", None)
        if external_type is not None and int(segment.type) == int(external_type):
            return "外部段函数"
    if cfg["skip_non_executable_segments"]:
        exec_permission = int(getattr(ida_segment, "SEGPERM_EXEC", 1))
        if int(segment.perm) & exec_permission == 0:
            return "不可执行段函数"
    if cfg["skip_imported_functions"] and ea in import_addresses:
        return "导入函数"
    if cfg["skip_ida_library_functions"] and int(func.flags) & int(ida_funcs.FUNC_LIB):
        return "IDA 库签名识别函数"
    if cfg["skip_thunks"] and int(func.flags) & int(ida_funcs.FUNC_THUNK):
        return "跳板函数（thunk）"
    if cfg["include_segments"] and not segment_matches(segment_name, cfg["include_segments"]):
        return "所属段不在包含列表中"
    if segment_matches(segment_name, cfg["exclude_segments"]):
        return "所属段已被排除"
    force_include = starts_with_any(names, cfg["force_include_prefixes"], cfg["case_sensitive_filters"])
    if not force_include:
        custom_reason = matches_exclude_filters(names, cfg)
        if custom_reason:
            return custom_reason
        if cfg["skip_standard_cpp_names"] and is_standard_cpp(names):
            return "C++ 标准库函数名称"
        if cfg["skip_common_c_names"] and is_common_c(names):
            return "常见 C 标准库函数名称"
        if cfg["skip_runtime_helpers"] and is_runtime(names):
            return "编译器或运行时辅助函数"
        if cfg["skip_known_third_party_names"] and is_third_party(names):
            return "已知第三方模块函数名称"
        if cfg["skip_autogenerated_names"] and is_autogenerated(raw_name):
            return "IDA 自动生成函数名称"
    length = int(func.end_ea) - int(func.start_ea)
    if cfg["minimum_function_length"] and length < cfg["minimum_function_length"]:
        return f"函数长度 0x{length:X} 小于最小限制 0x{cfg['minimum_function_length']:X}"
    if cfg["maximum_function_length"] and length > cfg["maximum_function_length"]:
        return f"函数长度 0x{length:X} 超过最大限制 0x{cfg['maximum_function_length']:X}"
    return None


def collect_retained_pool(import_addresses: Set[int], cfg: dict) -> Tuple[Dict[int, ExportTarget], List[SkippedTarget]]:
    retained: Dict[int, ExportTarget] = {}
    skipped: List[SkippedTarget] = []
    seen: Set[int] = set()
    for candidate_ea in idautils.Functions():
        func = ida_funcs.get_func(candidate_ea)
        if func is None:
            continue
        start_ea = int(func.start_ea)
        if start_ea in seen:
            continue
        seen.add(start_ea)
        raw_name = ida_funcs.get_func_name(start_ea) or f"sub_{start_ea:X}"
        segment_name = get_segment_name(start_ea)
        reason = classify_skip(func, import_addresses, cfg)
        if reason:
            skipped.append(SkippedTarget(start_ea, raw_name, segment_name, reason))
            continue
        demangled = try_demangle(raw_name)
        retained[start_ea] = ExportTarget(start_ea, int(func.end_ea), raw_name, demangled or raw_name, segment_name, int(func.flags))
    return retained, sorted(skipped, key=lambda item: item.start_ea)


def collect_direct_dependencies(ea: int, retained: Dict[int, ExportTarget], cache: Dict[int, Set[int]]) -> Set[int]:
    if ea in cache:
        return cache[ea]
    deps: Set[int] = set()
    try:
        items = idautils.FuncItems(ea)
    except Exception:
        cache[ea] = deps
        return deps
    for item_ea in items:
        try:
            refs = idautils.CodeRefsFrom(item_ea, False)
        except Exception:
            continue
        for ref_ea in refs:
            try:
                func = ida_funcs.get_func(ref_ea)
            except Exception:
                func = None
            if func is None:
                continue
            callee = int(func.start_ea)
            if callee != ea and callee in retained:
                deps.add(callee)
    cache[ea] = deps
    return deps


def expand_dependencies(roots: Iterable[int], retained: Dict[int, ExportTarget], maximum_depth: int) -> Tuple[Set[int], Set[Tuple[int, int]]]:
    selected: Set[int] = set()
    edges: Set[Tuple[int, int]] = set()
    cache: Dict[int, Set[int]] = {}
    queue = deque()
    for ea in roots:
        if ea in retained and ea not in selected:
            selected.add(ea)
            queue.append((ea, 0))
    while queue:
        caller, depth = queue.popleft()
        if maximum_depth and depth >= maximum_depth:
            continue
        for callee in collect_direct_dependencies(caller, retained, cache):
            edges.add((caller, callee))
            if callee not in selected:
                selected.add(callee)
                queue.append((callee, depth + 1))
    return selected, edges


def resolve_scope_targets(retained: Dict[int, ExportTarget], cfg: dict) -> Tuple[List[ExportTarget], int, Set[Tuple[int, int]]]:
    scope = cfg["scope"]
    if scope == "all_internal":
        targets = sorted(retained.values(), key=lambda item: item.start_ea)
        return targets, len(targets), set()
    roots: Set[int]
    if scope.startswith("matched_"):
        roots = {ea for ea, target in retained.items() if matches_include_filters(symbol_names(target.raw_name), cfg)}
    elif scope.startswith("current_"):
        current_func = ida_funcs.get_func(int(ida_kernwin.get_screen_ea()))
        if current_func is None:
            raise RuntimeError("当前光标不在 IDA 已识别函数内部。")
        start_ea = int(current_func.start_ea)
        if start_ea not in retained:
            raise RuntimeError("当前函数已被筛选条件排除。")
        roots = {start_ea}
    elif scope.startswith("range_"):
        start, end = parse_integer(cfg["range_start"]), parse_integer(cfg["range_end"])
        roots = {ea for ea, target in retained.items() if target.start_ea < end and target.end_ea > start}
    else:
        raise RuntimeError(f"不支持的导出范围：{scope}")
    root_count = len(roots)
    if scope.endswith("_with_dependencies"):
        selected, edges = expand_dependencies(roots, retained, cfg["maximum_dependency_depth"])
    else:
        selected, edges = roots, set()
    targets = sorted((retained[ea] for ea in selected), key=lambda item: item.start_ea)
    return targets, root_count, edges


def sanitize_filename_component(value: str) -> str:
    safe = re.sub(r'[<>:"/\\|?*\x00-\x1F]', "_", value)
    safe = re.sub(r"\s+", "_", safe.strip(" .")) or "unnamed"
    return f"_{safe}" if safe.upper() in WINDOWS_RESERVED_NAMES else safe


def get_auto_path_budget(cfg: dict) -> int:
    """返回内部安全路径预算。普通用户无需填写路径长度。"""
    override = int(cfg.get("internal_path_budget_override", 0) or 0)
    if override > 0:
        return max(160, override)
    # Windows 兼容预算偏保守，避免旧环境或未启用长路径策略时失败。
    return 238 if os.name == "nt" else 1024


def path_fits_budget(path: Path, cfg: dict, reserve: int = 0) -> bool:
    return len(str(path)) + int(reserve) <= get_auto_path_budget(cfg)


def get_compact_storage_root(seed_path: Path, cfg: dict) -> Path:
    """在用户选择的目录过深时自动选择短路径存储根目录。"""
    configured = str(cfg.get("compact_output_root") or "").strip()
    digest = hashlib.sha1(str(seed_path).encode("utf-8", errors="replace")).hexdigest()[:10]
    candidates: List[Path] = []
    if configured:
        candidates.append(Path(configured) / digest)
    if os.name == "nt":
        anchor = Path(seed_path.anchor) if seed_path.anchor else Path.cwd().anchor
        if str(anchor):
            candidates.append(Path(anchor) / "IDAExport" / digest)
    candidates.append(Path(tempfile.gettempdir()) / "IDAExport" / digest)
    for candidate in candidates:
        try:
            candidate.mkdir(parents=True, exist_ok=True)
            return candidate
        except Exception:
            continue
    raise RuntimeError("无法自动创建短路径输出目录。请将输出根目录改为较短且可写的位置。")


def write_redirect_note(requested_root: Path, actual_root: Path, run_name: str) -> None:
    """尽力在用户原始目录中写入跳转说明；失败不会阻止导出。"""
    try:
        requested_root.mkdir(parents=True, exist_ok=True)
        note = requested_root / f"IDA_EXPORT_REDIRECT_{run_name}.txt"
        note.write_text(
            "检测到输出路径过长，插件已自动切换到短路径目录。\n"
            f"实际输出目录：{actual_root}\n",
            encoding="utf-8",
        )
    except Exception:
        pass


def shorten_directory_component(value: str, maximum_length: int) -> str:
    """生成安全且长度受控的类目录片段。"""
    safe = sanitize_filename_component(value)
    if len(safe) <= maximum_length:
        return safe
    digest = hashlib.sha1(safe.encode("utf-8", errors="replace")).hexdigest()[:8]
    keep = max(1, maximum_length - len(digest) - 1)
    return f"{safe[:keep]}_{digest}"


def extract_class_owner_components(target: ExportTarget, cfg: dict) -> List[str]:
    """
    从反编译显示名称中提取命名空间 / 类目录。

    示例：
    - demo::Document::Save(...) -> [demo, Document]
    - Document::Close() -> [Document]
    - `anonymous namespace'::CompressBitmap(...) -> [_anonymous_namespace]
    - sub_1234 -> [_autogenerated]
    - global_function() -> [_global]
    """
    raw = str(target.display_name or target.raw_name or "").strip()
    if re.match(r"^(sub_|nullsub_|loc_|j_|unknown_|func_)", raw):
        return ["_autogenerated"]

    normalized = (
        raw.replace("`anonymous namespace'", "_anonymous_namespace")
           .replace("(anonymous namespace)", "_anonymous_namespace")
           .replace("anonymous namespace", "_anonymous_namespace")
    )
    # 只取签名头部，最后一个 :: 片段视为函数名称。
    signature_head = normalized.split("(", 1)[0].strip()
    if "::" not in signature_head:
        return ["_global"]

    owners = [part.strip() for part in signature_head.split("::")[:-1] if part.strip()]
    if not owners:
        return ["_global"]
    if not cfg.get("class_folder_include_namespaces", True):
        owners = [owners[-1]]

    maximum = int(cfg.get("class_folder_component_length", 48) or 48)
    return [shorten_directory_component(part, maximum) for part in owners]


def get_class_category(target: ExportTarget, cfg: dict) -> str:
    return "/".join(extract_class_owner_components(target, cfg))


def get_batch_folder_name(target_ordinal: int, cfg: dict) -> str:
    """根据目标函数序号生成稳定的批次目录名称，例如 batch_0001。"""
    if not cfg.get("group_files_by_batch", True):
        return ""
    per_folder = max(1, int(cfg.get("functions_per_batch_folder", 1000) or 1000))
    batch_number = ((max(1, int(target_ordinal)) - 1) // per_folder) + 1
    return f"batch_{batch_number:04d}"


def resolve_function_output_dir(
    function_root: Path,
    target: ExportTarget,
    cfg: dict,
    target_ordinal: int = 1,
) -> Tuple[Path, str, str]:
    """
    自动建立批次、段名称和类名称目录。

    路径较长时会自动逐级缩短目录，不要求用户手工填写长度限制。
    最终完整类名仍保存在 CSV 和 .c 文件头中。
    """
    batch_folder = get_batch_folder_name(target_ordinal, cfg)
    class_category = get_class_category(target, cfg)

    def build_parts(component_limit: int, include_class: bool = True) -> List[str]:
        parts: List[str] = []
        if batch_folder:
            parts.append(batch_folder)
        if cfg.get("group_files_by_segment", False):
            parts.append(shorten_directory_component(target.segment_name or "_no_segment", min(40, component_limit)))
        if include_class and cfg.get("group_files_by_class", True):
            raw_cfg = dict(cfg)
            raw_cfg["class_folder_component_length"] = component_limit
            parts.extend(extract_class_owner_components(target, raw_cfg))
        return parts

    # 先尽量保留较长的可读目录，再逐级缩短。
    for limit in (96, 72, 56, 40, 28, 20, 16):
        parts = build_parts(limit, include_class=True)
        candidate = function_root.joinpath(*parts) if parts else function_root
        if path_fits_budget(candidate, cfg, reserve=64):
            candidate.mkdir(parents=True, exist_ok=True)
            return candidate, class_category, batch_folder

    # 类目录仍然过长时，使用类名哈希兜底。
    digest = hashlib.sha1(class_category.encode("utf-8", errors="replace")).hexdigest()[:10]
    parts = build_parts(20, include_class=False)
    parts.append(f"_class_{digest}")
    candidate = function_root.joinpath(*parts)
    if path_fits_budget(candidate, cfg, reserve=48):
        candidate.mkdir(parents=True, exist_ok=True)
        return candidate, class_category, batch_folder

    # 最终退化为极短目录。
    candidate = function_root / "_short" / (batch_folder or "batch_none")
    candidate.mkdir(parents=True, exist_ok=True)
    return candidate, class_category, batch_folder


def make_safe_filename(directory: Path, target: ExportTarget, cfg: dict) -> str:
    """自动生成安全文件名：可读名称优先，必要时退化为地址与哈希。"""
    digest = hashlib.sha1(f"{target.start_ea:X}:{target.raw_name}".encode("utf-8", errors="replace")).hexdigest()[:10]
    address = f"{target.start_ea:016X}"
    shortest = f"{address}_{digest}.c"
    if cfg.get("filename_mode") == "address_only":
        filename = shortest
    else:
        readable = sanitize_filename_component(target.display_name)
        prefix, suffix = f"{address}_", f"_{digest}.c"
        available = get_auto_path_budget(cfg) - len(str(directory)) - 1 - len(prefix) - len(suffix)
        internal_limit = int(cfg.get("maximum_readable_name_length", 160) or 160)
        keep = max(0, min(internal_limit, available))
        filename = f"{prefix}{readable[:keep]}{suffix}" if keep else shortest
    if not path_fits_budget(directory / filename, cfg):
        filename = shortest
    if not path_fits_budget(directory / filename, cfg):
        raise RuntimeError("自动缩短文件名后路径仍然过长。插件会在下一次运行自动切换到短路径存储目录。")
    return filename


def build_function_file(target: ExportTarget, pseudocode: str, class_category: str, batch_folder: str = "") -> str:
    return (
        "/*\n"
        " * Hex-Rays 单函数伪代码导出\n"
        f" * 地址        : 0x{target.start_ea:X}\n"
        f" * 长度        : 0x{target.length:X}\n"
        f" * 所属段      : {target.segment_name}\n"
        f" * 原始符号    : {target.raw_name}\n"
        f" * 显示名称    : {target.display_name}\n"
        f" * 类别目录    : {class_category}\n"
        f" * 批次目录    : {batch_folder or '_none'}\n"
        " * 导出范围    : 当前函数体；依赖函数保存在其他独立文件中\n"
        " * 说明        : 这是反编译器生成的伪代码，不是原始源代码\n"
        " */\n\n" + pseudocode
    )


def get_pseudocode(ea: int) -> str:
    """
    仅提取纯文本，不手工调用 cfunc.release()。

    cfunc_t 是 SWIG / 引用计数包装对象。为了降低长时间批量运行时的
    生命周期风险，文本提取完成后仅让 Python 引用离开作用域，再由
    cleanup_hexrays_cache() 主动清理 Hex-Rays 缓存。
    """
    cfunc = ida_hexrays.decompile(ea)
    if cfunc is None:
        raise RuntimeError("Hex-Rays 未返回伪代码。")
    lines: List[str] = []
    for line in cfunc.get_pseudocode():
        try:
            lines.append(ida_lines.tag_remove(line.line))
        except Exception as exc:
            lines.append(f"// [伪代码行转换失败：{exc!r}]")
    return "\n".join(lines).rstrip() + "\n"


def decompile_with_retry(target: ExportTarget, cfg: dict) -> str:
    try:
        return get_pseudocode(target.start_ea)
    except Exception:
        if not cfg["retry_failed_after_local_analysis"]:
            raise
        ida_auto.auto_wait_range(target.start_ea, target.end_ea)
        return get_pseudocode(target.start_ea)


def cleanup_hexrays_cache(target_ea: Optional[int], processed_count: int, cfg: dict, logger: Logger = default_logger, force_all: bool = False) -> None:
    if not cfg.get("stable_mode", True):
        return
    if target_ea is not None and cfg.get("clear_target_cache_after_each_function", True):
        try:
            ida_hexrays.mark_cfunc_dirty(int(target_ea), False)
        except Exception as exc:
            logger(f"警告：清理函数缓存 0x{int(target_ea):X} 失败：{exc}")
    interval = int(cfg.get("clear_all_cache_interval", 0) or 0)
    if force_all or (interval > 0 and processed_count > 0 and processed_count % interval == 0):
        try:
            ida_hexrays.clear_cached_cfuncs()
        except Exception as exc:
            logger(f"警告：清理全部 Hex-Rays 缓存失败：{exc}")
    gc_interval = int(cfg.get("python_gc_interval", 0) or 0)
    if force_all or (gc_interval > 0 and processed_count > 0 and processed_count % gc_interval == 0):
        gc.collect()
    cooldown = int(cfg.get("cooldown_milliseconds", 0) or 0)
    if cooldown > 0:
        time.sleep(cooldown / 1000.0)


def choose_run_dir(cfg: dict) -> Tuple[Path, Path]:
    """创建运行目录。路径过深时自动切换到短路径目录。"""
    resume = str(cfg.get("resume_run_dir") or "").strip()
    if resume:
        run_dir = Path(resume)
        run_dir.mkdir(parents=True, exist_ok=True)
    else:
        requested_root = Path(cfg["output_dir"]) if str(cfg.get("output_dir") or "").strip() else get_default_output_root()
        run_name = f"run_{timestamp_id()}"
        desired_run_dir = requested_root / run_name
        probe = desired_run_dir / "functions" / "_short" / "batch_none" / "0000000000000000_0000000000.c"
        if cfg.get("auto_compact_root_on_overflow", True) and not path_fits_budget(probe, cfg):
            compact_root = get_compact_storage_root(requested_root, cfg)
            run_dir = compact_root / run_name
            write_redirect_note(requested_root, run_dir, run_name)
        else:
            run_dir = desired_run_dir
        run_dir.mkdir(parents=True, exist_ok=True)
        try:
            (run_dir / "requested_output_root.txt").write_text(
                f"用户选择的输出根目录：{requested_root}\n实际运行目录：{run_dir}\n",
                encoding="utf-8",
            )
        except Exception:
            pass
    attempt_dir = run_dir / "attempts" / f"attempt_{timestamp_id()}"
    attempt_dir.mkdir(parents=True, exist_ok=True)
    return run_dir, attempt_dir


def resolve_function_root(run_dir: Path, cfg: dict) -> Path:
    """确保函数文件根目录足够短；必要时自动重定向到短路径存储目录。"""
    desired = run_dir / "functions"
    probe = desired / "_short" / "batch_none" / "0000000000000000_0000000000.c"
    if path_fits_budget(probe, cfg):
        desired.mkdir(parents=True, exist_ok=True)
        return desired
    compact = get_compact_storage_root(run_dir, cfg) / run_dir.name / "functions"
    compact.mkdir(parents=True, exist_ok=True)
    try:
        (run_dir / "functions_redirect.txt").write_text(
            "函数文件目录已自动重定向到短路径。\n"
            f"实际函数文件目录：{compact}\n",
            encoding="utf-8",
        )
    except Exception:
        pass
    return compact


def relative_or_absolute(path: Path, base: Path) -> str:
    try:
        return str(path.relative_to(base))
    except Exception:
        return str(path)


def write_csv(path: Path, header: Sequence[str], rows: Iterable[Sequence[object]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8-sig") as f:
        writer = csv.writer(f)
        writer.writerow(header)
        writer.writerows(rows)


def get_database_stem() -> str:
    try:
        path = get_database_path()
        if path.stem:
            return sanitize_filename_component(path.stem)
    except Exception:
        pass
    try:
        input_name = idc.get_root_filename() or idc.get_input_file_path() or "ida_database"
    except Exception:
        input_name = "ida_database"
    return sanitize_filename_component(Path(str(input_name)).stem or "ida_database")


def collect_all_function_name_records(logger: Logger = default_logger) -> List[dict]:
    import_addresses = collect_import_addresses(logger)
    records: List[dict] = []
    for index, ea in enumerate(idautils.Functions(), start=1):
        func = ida_funcs.get_func(ea)
        if func is None:
            continue
        start_ea = int(func.start_ea)
        end_ea = int(func.end_ea)
        raw_name = ida_funcs.get_func_name(start_ea) or f"sub_{start_ea:X}"
        demangled_name = try_demangle(raw_name)
        flags = int(func.flags)
        records.append({
            "index": len(records) + 1,
            "address": f"0x{start_ea:X}",
            "start_ea": start_ea,
            "end_ea": end_ea,
            "length": max(0, end_ea - start_ea),
            "segment": get_segment_name(start_ea),
            "raw_name": raw_name,
            "demangled_name": demangled_name,
            "display_name": demangled_name or raw_name,
            "flags": flags,
            "flags_hex": f"0x{flags:X}",
            "is_library": bool(flags & int(ida_funcs.FUNC_LIB)),
            "is_thunk": bool(flags & int(ida_funcs.FUNC_THUNK)),
            "is_import_name": start_ea in import_addresses,
        })
    records.sort(key=lambda item: int(item["start_ea"]))
    for index, item in enumerate(records, start=1):
        item["index"] = index
    return records


def export_all_function_names(output_root: Optional[str | Path] = None, logger: Logger = default_logger) -> Path:
    base_root = Path(output_root) if output_root else get_default_output_root()
    report_dir = base_root / f"function_names_{get_database_stem()}_{timestamp_id()}"
    report_dir.mkdir(parents=True, exist_ok=True)
    logger("正在枚举当前数据库中的全部函数名称……")
    records = collect_all_function_name_records(logger)
    header = [
        "index", "address", "start_ea", "end_ea", "length", "segment",
        "raw_name", "demangled_name", "display_name", "flags_hex",
        "is_library", "is_thunk", "is_import_name",
    ]
    write_csv(
        report_dir / "all_function_names.csv",
        header,
        ([record.get(key, "") for key in header] for record in records),
    )
    atomic_write_json(report_dir / "all_function_names.json", {"version": 1, "count": len(records), "items": records})
    atomic_write_text(report_dir / "all_function_raw_names.txt", "\n".join(str(item["raw_name"]) for item in records) + ("\n" if records else ""))
    atomic_write_text(report_dir / "all_function_display_names.txt", "\n".join(str(item["display_name"]) for item in records) + ("\n" if records else ""))
    summary_lines = [
        f"通用函数伪代码导出器核心 {CORE_VERSION}",
        "=" * 72,
        f"数据库名称                     : {get_database_stem()}",
        f"输出目录                       : {report_dir}",
        f"函数数量                       : {len(records)}",
        "",
        "输出文件：",
        "- all_function_names.csv：完整表格，含地址、段、原始名、反混淆名、标志位。",
        "- all_function_names.json：结构化 JSON。",
        "- all_function_raw_names.txt：仅原始函数名，一行一个。",
        "- all_function_display_names.txt：优先使用反混淆后的显示名，一行一个。",
    ]
    atomic_write_text(report_dir / "summary.txt", "\n".join(summary_lines) + "\n")
    logger(f"全部函数名称导出完成：{len(records)} 个函数，目录：{report_dir}")
    return report_dir


def write_selection_reports(attempt_dir: Path, retained: Dict[int, ExportTarget], skipped: Sequence[SkippedTarget], targets: Sequence[ExportTarget], edges: Set[Tuple[int, int]], cfg: dict) -> None:
    write_csv(
        attempt_dir / "selected_functions.csv",
        ["address", "length", "segment", "batch_folder", "class_category", "raw_symbol", "display_name"],
        ([f"0x{x.start_ea:X}", f"0x{x.length:X}", x.segment_name, get_batch_folder_name(index, cfg), get_class_category(x, cfg), x.raw_name, x.display_name] for index, x in enumerate(targets, start=1)),
    )
    write_csv(
        attempt_dir / "class_folder_mapping.csv",
        ["address", "batch_folder", "class_category", "raw_symbol", "display_name"],
        ([f"0x{x.start_ea:X}", get_batch_folder_name(index, cfg), get_class_category(x, cfg), x.raw_name, x.display_name] for index, x in enumerate(targets, start=1)),
    )
    write_csv(
        attempt_dir / "skipped_functions.csv",
        ["address", "segment", "reason", "raw_symbol"],
        ([f"0x{x.start_ea:X}", x.segment_name, x.reason, x.name] for x in skipped),
    )
    if cfg.get("write_dependency_edges", True):
        write_csv(attempt_dir / "dependency_edges.csv", ["caller", "callee"], ([f"0x{a:X}", f"0x{b:X}"] for a, b in sorted(edges)))
    counts = Counter(x.reason for x in skipped)
    lines = [
        "筛选统计", "=" * 72, f"保留函数池：{len(retained)}", f"最终目标函数：{len(targets)}", f"排除函数：{len(skipped)}", "", "排除原因统计："
    ]
    lines.extend(f"- {count}: {reason}" for reason, count in counts.most_common())
    (attempt_dir / "filter_summary.txt").write_text("\n".join(lines) + "\n", encoding="utf-8")


def load_quarantine(run_dir: Path) -> Dict[str, dict]:
    path = run_dir / "quarantined_functions.json"
    try:
        data = load_json(path)
        items = data.get("items", {}) if isinstance(data, dict) else {}
        return items if isinstance(items, dict) else {}
    except Exception:
        return {}


def save_quarantine(run_dir: Path, quarantine: Dict[str, dict]) -> None:
    atomic_write_json(run_dir / "quarantined_functions.json", {"version": 1, "items": quarantine})


def add_quarantine(run_dir: Path, address: int, name: str, reason: str, source: str) -> None:
    quarantine = load_quarantine(run_dir)
    key = f"0x{int(address):X}"
    quarantine[key] = {
        "address": int(address), "name": name, "reason": reason, "source": source, "updated_at": time.strftime("%Y-%m-%d %H:%M:%S")
    }
    save_quarantine(run_dir, quarantine)


def recover_previous_active_checkpoint(run_dir: Path, cfg: dict, logger: Logger = default_logger) -> Optional[int]:
    checkpoint_path = run_dir / "active_function_checkpoint.json"
    if not checkpoint_path.is_file() or not cfg.get("auto_quarantine_previous_active_on_resume", True):
        return None
    try:
        data = load_json(checkpoint_path)
        address = int(data.get("address"))
        name = str(data.get("name") or f"sub_{address:X}")
    except Exception:
        return None
    add_quarantine(run_dir, address, name, "上次 IDA 进程在处理该函数时异常终止，已自动隔离", "resume_checkpoint")
    logger(f"检测到上次未清理的崩溃检查点，已自动隔离函数：0x{address:X} {name}")
    try:
        checkpoint_path.unlink()
    except Exception:
        pass
    return address


def write_active_checkpoint(run_dir: Path, target: ExportTarget, session_id: str = "interactive") -> None:
    atomic_write_json(
        run_dir / "active_function_checkpoint.json",
        {
            "address": target.start_ea,
            "name": target.raw_name,
            "session_id": session_id,
            "pid": os.getpid(),
            "started_at": time.strftime("%Y-%m-%d %H:%M:%S"),
        },
    )


def clear_active_checkpoint(run_dir: Path) -> None:
    path = run_dir / "active_function_checkpoint.json"
    try:
        if path.exists():
            path.unlink()
    except Exception:
        pass


def write_progress_state(run_dir: Path, session_id: str, stats: ExportStats, current_address: Optional[int], remaining_addresses: Sequence[int]) -> None:
    atomic_write_json(
        run_dir / f"progress_state_{session_id}.json",
        {
            "session_id": session_id,
            "pid": os.getpid(),
            "updated_at": time.strftime("%Y-%m-%d %H:%M:%S"),
            "stats": asdict(stats),
            "current_address": current_address,
            "remaining_addresses": list(remaining_addresses),
        },
    )


def write_summary(path: Path, run_dir: Path, attempt_dir: Path, cfg: dict, stats: ExportStats, failures: Counter) -> None:
    lines = [
        f"通用函数伪代码导出器核心 {CORE_VERSION}", "=" * 72,
        f"运行目录                       : {run_dir}",
        f"本次尝试目录                   : {attempt_dir}",
        f"目标函数数量                   : {stats.target_count}",
        f"成功导出                       : {stats.exported_count}",
        f"已有文件                       : {stats.existing_count}",
        f"失败                           : {stats.failed_count}",
        f"隔离跳过                       : {stats.quarantined_count}",
        f"用户取消                       : {stats.cancelled}",
        f"达到单次会话处理上限           : {stats.session_limit_reached}",
        f"按批次目录分组                 : {cfg.get('group_files_by_batch', True)}",
        f"每个批次目录函数数量           : {cfg.get('functions_per_batch_folder', 1000)}",
        f"路径自动优化                   : {cfg.get('auto_path_shortening', True)}",
        f"路径过长自动切换短目录         : {cfg.get('auto_compact_root_on_overflow', True)}",
        "", "失败原因统计：",
    ]
    if failures:
        lines.extend(f"- {count}: {reason}" for reason, count in failures.most_common())
    else:
        lines.append("- 无")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def process_targets(
    targets: Sequence[ExportTarget],
    cfg: dict,
    run_dir: Path,
    attempt_dir: Path,
    session_id: str = "interactive",
    logger: Logger = default_logger,
    cancel_checker: Optional[CancelChecker] = None,
    progress_callback: Optional[ProgressCallback] = None,
) -> ProcessResult:
    """逐函数导出。硬崩溃时 active checkpoint 会保留，供续导自动隔离。"""
    function_root = resolve_function_root(run_dir, cfg)
    recover_previous_active_checkpoint(run_dir, cfg, logger)
    quarantine = load_quarantine(run_dir)
    quarantine_addresses = {int(item["address"]) for item in quarantine.values() if isinstance(item, dict) and "address" in item}
    stats = ExportStats(target_count=len(targets))
    failures: Counter = Counter()
    remaining_addresses = [target.start_ea for target in targets]
    attempt_index = attempt_dir / f"export_index_{session_id}.csv"
    manifest_path = run_dir / f"manifest_{session_id}.csv"
    failed_path = attempt_dir / f"failed_functions_{session_id}.log"
    result_jsonl = run_dir / f"completed_{session_id}.jsonl"
    header = ["session", "address", "length", "segment", "batch_folder", "class_category", "raw_symbol", "display_name", "status", "output_file", "details"]
    manifest_exists = manifest_path.exists()
    processed_in_session = 0

    with attempt_index.open("w", newline="", encoding="utf-8-sig") as attempt_file, \
         manifest_path.open("a", newline="", encoding="utf-8-sig") as manifest_file, \
         failed_path.open("w", encoding="utf-8") as failed_file:
        attempt_writer, manifest_writer = csv.writer(attempt_file), csv.writer(manifest_file)
        attempt_writer.writerow(header)
        if not manifest_exists:
            manifest_writer.writerow(header)

        for index, target in enumerate(targets, start=1):
            remaining_addresses = [item.start_ea for item in targets[index - 1:]]
            if cancel_checker is not None and cancel_checker():
                stats.cancelled = True
                logger("用户已取消导出，将在当前安全点停止。")
                break
            if cfg.get("maximum_functions_per_session", 0) and processed_in_session >= int(cfg["maximum_functions_per_session"]):
                stats.session_limit_reached = True
                logger("已达到单次会话处理上限，将保存进度并退出本次会话。")
                break
            if progress_callback is not None:
                progress_callback(index, len(targets), stats, target)

            output_dir, class_category, batch_folder = resolve_function_output_dir(function_root, target, cfg, index)
            filename = make_safe_filename(output_dir, target, cfg)
            output_path = output_dir / filename
            relative_path = relative_or_absolute(output_path, run_dir)
            row: List[object]

            if target.start_ea in quarantine_addresses:
                stats.quarantined_count += 1
                row = [session_id, f"0x{target.start_ea:X}", f"0x{target.length:X}", target.segment_name, batch_folder, class_category, target.raw_name, target.display_name, "quarantined", "", "已在隔离列表中"]
            elif cfg.get("skip_existing_files_when_resuming", True) and output_path.is_file() and output_path.stat().st_size > 0:
                stats.existing_count += 1
                row = [session_id, f"0x{target.start_ea:X}", f"0x{target.length:X}", target.segment_name, batch_folder, class_category, target.raw_name, target.display_name, "existing", relative_path, ""]
            else:
                if cfg.get("write_active_checkpoint", True):
                    write_active_checkpoint(run_dir, target, session_id)
                try:
                    pseudocode = decompile_with_retry(target, cfg)
                    atomic_write_text(output_path, build_function_file(target, pseudocode, class_category, batch_folder))
                    stats.exported_count += 1
                    row = [session_id, f"0x{target.start_ea:X}", f"0x{target.length:X}", target.segment_name, batch_folder, class_category, target.raw_name, target.display_name, "exported", relative_path, ""]
                except Exception as exc:
                    stats.failed_count += 1
                    reason = f"{type(exc).__name__}: {exc}"
                    failures[reason] += 1
                    failed_file.write(f"0x{target.start_ea:X}\t{target.raw_name}\t{reason}\n")
                    if cfg.get("write_tracebacks", False):
                        failed_file.write(traceback.format_exc() + "\n" + ("-" * 100) + "\n")
                    row = [session_id, f"0x{target.start_ea:X}", f"0x{target.length:X}", target.segment_name, batch_folder, class_category, target.raw_name, target.display_name, "failed", "", reason]
                finally:
                    processed_in_session += 1
                    cleanup_hexrays_cache(target.start_ea, processed_in_session, cfg, logger)
                    clear_active_checkpoint(run_dir)

            attempt_writer.writerow(row)
            manifest_writer.writerow(row)
            append_jsonl(result_jsonl, {"session_id": session_id, "address": target.start_ea, "status": row[8], "output_file": row[9], "details": row[10]})
            remaining_addresses = [item.start_ea for item in targets[index:]]
            write_progress_state(run_dir, session_id, stats, None, remaining_addresses)
            if index % int(cfg.get("flush_interval", 10)) == 0:
                attempt_file.flush()
                manifest_file.flush()
                failed_file.flush()
            if index == 1 or index % int(cfg.get("progress_update_interval", 50)) == 0 or index == len(targets):
                logger(f"session={session_id} 进度 {index}/{len(targets)}，成功={stats.exported_count}，已有={stats.existing_count}，失败={stats.failed_count}，隔离={stats.quarantined_count}")

    cleanup_hexrays_cache(None, processed_in_session, cfg, logger, force_all=True)
    remaining_addresses = [ea for ea in remaining_addresses if ea not in quarantine_addresses]
    write_progress_state(run_dir, session_id, stats, None, remaining_addresses)
    write_summary(attempt_dir / f"summary_{session_id}.txt", run_dir, attempt_dir, cfg, stats, failures)
    return ProcessResult(stats, failures, run_dir, attempt_dir, remaining_addresses, sorted(quarantine_addresses))


def prepare_targets(cfg: dict, logger: Logger = default_logger) -> Tuple[Dict[int, ExportTarget], List[SkippedTarget], List[ExportTarget], int, Set[Tuple[int, int]], Set[int]]:
    validate_config(cfg)
    logger("正在收集导入函数地址……")
    imports = collect_import_addresses(logger)
    logger("正在枚举函数并应用筛选条件……")
    retained, skipped = collect_retained_pool(imports, cfg)
    targets, root_count, edges = resolve_scope_targets(retained, cfg)
    if not targets:
        raise RuntimeError("筛选后没有可导出的函数。")
    if cfg["maximum_export_count"] and len(targets) > cfg["maximum_export_count"]:
        raise RuntimeError(f"目标函数数量 {len(targets)} 超过安全上限 {cfg['maximum_export_count']}。")
    return retained, skipped, targets, root_count, edges, imports



def create_export_attempt(cfg: dict, logger: Logger = default_logger) -> Tuple[Path, Path, Dict[int, ExportTarget], List[SkippedTarget], List[ExportTarget], int, Set[Tuple[int, int]], Set[int]]:
    run_dir, attempt_dir = choose_run_dir(cfg)
    retained, skipped, targets, root_count, edges, imports = prepare_targets(cfg, logger)
    attempt_dir.mkdir(parents=True, exist_ok=True)
    atomic_write_json(attempt_dir / "config_used.json", cfg)
    write_selection_reports(attempt_dir, retained, skipped, targets, edges, cfg)
    return run_dir, attempt_dir, retained, skipped, targets, root_count, edges, imports
